### PR TITLE
Initialize user data when a user is first created

### LINKED ISSUE #49: Create Cloud Function to initialize user profile data on user creation
As I realized when working on #20, user profile data needs to be initialized when a user is created. This can be achieved using a Cloud Function that is [triggered on user creation](https://firebase.google.com/docs/functions/auth-events#trigger_a_function_on_user_creation) (the same link provides info on a trigger when a user is deleted).

## Requirements
- The `uid` and `username` fields need to be populated in the `Users/<uid>` document when a user is created.
- The `Users/<uid>` document should be deleted when a user is deleted.
- Add tests that exercise both of the above requirements

### PR DESCRIPTION
**Pull request by eeeeeric**
Resolves #49

When a user signs in for the first time, the user document under `Users/<uid>` is created and initialized with the `uid`, `username`, and `profile_picture` fields (although the picture URL may be undefined if the auth method does not provide it).

When a user is deleted, the associated user document is deleted as well.

Automated tests were added to cover these features.

### CODE REVIEW

**Comment by eeeeeric** [comment]
Worth mentioning that this branch is based on my other cloud-functions branch, which has not been merged yet. The PR shows as a review for merging into that other branch, but obviously I want it to merge to master (eventually). Basing the PR off of master will show changes from #56 too, which I didn't want.

**Comment by hrecker** [comment]
Looks good!

**Comment by acmorales** [comment]
Yeah, looks all good here 👍  So does the UI need to call the `create/deleteUser` functions or are they invoked automatically when a document is created under `Users/`?

**Comment by eeeeeric** [comment]
@acmorales The UI does not need to do anything to trigger these functions. They are invoked automatically when a user is created in Firebase, which is going to be when they sign in for the first time using Google.

Thanks for the timely review y'all!

**Pull request merged**
