### PR TITLE
Exile graveyard

### LINKED ISSUE #37: Make highlighted-card in the SideZone modal actually change in User Input

### PR DESCRIPTION
**Pull request by vyhuang**
Pull request for placeholder implementation of graveyard/exile zone modals. Resolves #37.

### CODE REVIEW

**Comment by akdombrowski** [comment]
I added client/package-lock.json to .gitignore in my last commit. It doesn't look like you have that change in your repository. Have you done a recent pull? 

Unless others oppose, I think we should not push the package-lock.json file. It can be generated locally by running npm install with an up to date package.json file. The package-lock file isn't guaranteed to be generated in the same way and we don't need to worry about resolving conflicts in that file while we're in the development phase.

**Comment by eeeeeric** [comment]
My understanding is that the lock file should be committed since it’s purpose is to provide determinism during the build process - https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by akdombrowski** [comment]
There is an argument that we should do it so that we tightly restrict what versions of packages everyone is using, but I don't think we need that level of granularity and it causes extra problems if two people working on a project get different versions of a package because it says take at least <some version> and there are more than one available.

Here's one way that it causes extra work:
https://docs.npmjs.com/files/package-locks

Resolving lockfile conflicts§
Occasionally, two separate npm install will create package locks that cause merge conflicts in source control systems. As of npm@5.7.0, these conflicts can be resolved by manually fixing any package.json conflicts, and then running npm install [--package-lock-only] again. npm will automatically resolve any conflicts for you and write a merged package lock that includes all the dependencies from both branches in a reasonable tree. If --package-lock-only is provided, it will do this without also modifying your local node_modules/.

To make this process seamless on git, consider installing npm-merge-driver, which will teach git how to do this itself without any user interaction. In short: $ npx npm-merge-driver install -g will let you do this, and even works with pre-npm@5.7.0 versions of npm 5, albeit a bit more noisily. Note that if package.json itself conflicts, you will have to resolve that by hand and run npm install manually, even with the merge driver.

Another argument against is that it might hide issues from us in versions we're not using. The package-lock.json says exactly what versions of packages and dependencies to use. To make use of improvements and upgrades of new packages, we'll want to know if something fails on any version that we allow.

https://github.com/npm/npm/issues/20603

**Comment by eeeeeric** [comment]
IMO node is just terrible at dependency management - since the norm seems to be to specify dependency ranges, under the assumption that semver is followed correctly all the time. Otherwise this wouldn’t even be a problem.

Regarding your argument against, I don’t get it. If we depend on version A, why should we care that our existing code does not work with version B? If someone were to update the dependency, it’s their responsibility to ensure that the upgrade is compatible and if not, make any necessary changes. It may not even be possible to be compatible with both versions at once.

That said, I am not strongly opposed to removing the UI's package lock file. That should be up to the other people working on the UI.

**Comment by akdombrowski** [comment]
You can't publish package-lock.json file to npm, so if someone were to download it from npm, they would run npm install and it would check our package.json file for what dependencies and what versions we to download. Nearly all of our dependencies make use of the caret, so it's not deterministic what version they'll download and install with, other than the first number in the version. 

If package.json says "react": "^16.6.3", then any of the 16.x.x versions could be downloaded and installed. 

We might be able to discover that 16.7.2 doesn't work because someone got that version when they installed if we restricted everyone to 16.7.3.

I've already had difficulty merging it since it's more fine grained than just package.json.

**Comment by vyhuang** [comment]
I'm pretty sure when I originally put up this pull request, I hadn't merged master with my branch, which would explain why package-lock.json wasn't in the gitignore. That's been done now.

**Comment by acmorales** [comment]
I think we'll be ok omitting package-lock at this stage of development. A lot of our branches introduce several dependencies at a time. I think once we've gotten to a point where we've built out more of our UI, we should start committing it again. It'll be useful if we ever have a live production build of Mystic Get Together running; we'll be able to have the exact same dependency tree as production.

**Pull request merged**
